sudo: required
language: python
dist: trusty
python:
  - "3.6"
cache:
  - pip: true
  - directories:
    - $HOME/.parity-bin/
services:
  - postgresql
  - rabbitmq
before_install:
  - sudo apt-get install -y dpkg
  - tests/setup/setup_psql.sh
  - tests/setup/setup_rabbitmq.sh
  - tests/setup/setup_parity.sh
install:
  - travis_retry pip install -e . -r requirements.txt
script:
- python -m pytest -vv tests/infura
- python -m pytest -svv tests/parity
